"""Evaluator-only Gate 07 correspondence records.

The boundary is intentionally honest: repository readers can inspect this
module, but baseline arms receive only ``MethodFacingTask`` and never import
this package. Every accessor requires the same runtime capability type used by
Gate 06.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass
import hashlib
import json
from functools import lru_cache

from research.gate0.evaluator.capability import EvaluatorCapability

from research.gate07.dataset.generator import build_all_cases


@dataclass(frozen=True)
class Gate07GroundTruth:
    case_id: str
    family: str
    old_tool_names: tuple[str, ...]
    correct_new_tool_names: tuple[str, ...]
    argument_pairs: tuple[tuple[str, str, str, str], ...]
    new_only_required_fields: tuple[str, ...]
    expected_effect_kinds: tuple[str, ...]
    output_field_mapping: tuple[tuple[str, str], ...]
    rationale: str


@lru_cache(maxsize=1)
def _build_ground_truth() -> dict[str, Gate07GroundTruth]:
    return {
        case.case_id: Gate07GroundTruth(
            case_id=case.case_id,
            family=case.family,
            old_tool_names=case.old_tool_names,
            correct_new_tool_names=case.new_tool_names,
            argument_pairs=case.argument_pairs,
            new_only_required_fields=case.new_only_required_fields,
            expected_effect_kinds=case.expected_effect_kinds,
            output_field_mapping=case.output_field_mapping,
            rationale=f"Generated by the frozen executed lineage {case.lineage_key}.",
        )
        for case in build_all_cases()
    }


def get_ground_truth(case_id: str, capability: EvaluatorCapability) -> Gate07GroundTruth:
    if not isinstance(capability, EvaluatorCapability):
        raise PermissionError("Gate 07 ground truth requires a real EvaluatorCapability instance.")
    try:
        return _build_ground_truth()[case_id]
    except KeyError as exc:
        raise KeyError(f"No Gate 07 ground truth for {case_id!r}.") from exc


def all_ground_truth(capability: EvaluatorCapability, *, graded_only: bool = False) -> tuple[Gate07GroundTruth, ...]:
    if not isinstance(capability, EvaluatorCapability):
        raise PermissionError("Gate 07 ground truth requires a real EvaluatorCapability instance.")
    values = tuple(_build_ground_truth().values())
    if graded_only:
        return tuple(value for value in values if value.case_id.startswith("G07-G-"))
    return values


def ground_truth_digest(capability: EvaluatorCapability, *, graded_only: bool = False) -> str:
    records = [asdict(value) for value in all_ground_truth(capability, graded_only=graded_only)]
    canonical = json.dumps(records, ensure_ascii=True, sort_keys=True, separators=(",", ":"))
    return f"sha256:{hashlib.sha256(canonical.encode('utf-8')).hexdigest()}"
