"""Curated public source catalog for VietRAGOps Phase 1."""

SOURCE_CATALOG = [
    {
        "doc_id": "ug_academic_hub",
        "source_url": "https://undergrad.tdtu.edu.vn/hoc-vu",
        "source_type": "html",
        "domain": "student_guide",
        "authority_level": "official",
        "status": "active",
        "notes": "Official undergraduate academics landing page.",
    },
    {
        "doc_id": "ug_guidance_hub",
        "source_url": "https://undergrad.tdtu.edu.vn/huong-dan/hoc-vu",
        "source_type": "html",
        "domain": "student_guide",
        "authority_level": "official",
        "status": "active",
        "notes": "Official academic guidance hub.",
    },
    {
        "doc_id": "ug_things_to_know",
        "source_url": "https://undergrad.tdtu.edu.vn/huong-dan/nhung-dieu-can-biet-khi-hoc-tai-tdtu",
        "source_type": "html",
        "domain": "student_guide",
        "authority_level": "official",
        "status": "active",
        "notes": "Public student guide overview.",
    },
    {
        "doc_id": "ug_student_portal_guide",
        "source_url": "https://undergrad.tdtu.edu.vn/huong-dan/huong-dan-dang-nhap-va-su-dung-he-thong-thong-tin-sinh-vien",
        "source_type": "html",
        "domain": "student_account",
        "authority_level": "official",
        "status": "active",
        "notes": "Public guide to the student information portal.",
    },
    {
        "doc_id": "ug_student_email_guide",
        "source_url": "https://undergrad.tdtu.edu.vn/huong-dan/email-sinh-vien-tdtu",
        "source_type": "html",
        "domain": "email_usage",
        "authority_level": "official",
        "status": "active",
        "notes": "Public student email guidance.",
    },
    {
        "doc_id": "ug_study_path_guide",
        "source_url": "https://undergrad.tdtu.edu.vn/huong-dan/huong-dan-xem-so-do-dao-tao",
        "source_type": "html",
        "domain": "curriculum",
        "authority_level": "official",
        "status": "active",
        "notes": "Guide to viewing the training roadmap.",
    },
    {
        "doc_id": "ug_academic_year_plan_guide",
        "source_url": "https://undergrad.tdtu.edu.vn/huong-dan/huong-dan-xem-ke-hoach-thoi-gian-nam-hoc",
        "source_type": "html",
        "domain": "academic_schedule",
        "authority_level": "official",
        "status": "active",
        "notes": "Guide to checking the academic year plan.",
    },
    {
        "doc_id": "ug_study_plan_registration_guide",
        "source_url": "https://undergrad.tdtu.edu.vn/huong-dan/huong-dan-sv-dang-ky-ke-hoach-hoc-tap",
        "source_type": "html",
        "domain": "course_registration",
        "authority_level": "official",
        "status": "active",
        "notes": "Guide to registering a study plan.",
    },
    {
        "doc_id": "ug_course_registration_guide",
        "source_url": "https://undergrad.tdtu.edu.vn/huong-dan/huong-dan-sv-dang-ky-mon-hoc",
        "source_type": "html",
        "domain": "course_registration",
        "authority_level": "official",
        "status": "active",
        "notes": "Guide to course registration.",
    },
    {
        "doc_id": "ug_timetable_guide",
        "source_url": "https://undergrad.tdtu.edu.vn/huong-dan/huong-dan-xem-thoi-khoa-bieu",
        "source_type": "html",
        "domain": "academic_schedule",
        "authority_level": "official",
        "status": "active",
        "notes": "Guide to checking the timetable.",
    },
    {
        "doc_id": "ug_graduation_conditions",
        "source_url": "https://undergrad.tdtu.edu.vn/huong-dan/dieu-kien-duoc-xet-cong-nhan-tot-nghiep",
        "source_type": "html",
        "domain": "graduation_requirement",
        "authority_level": "official",
        "status": "active",
        "notes": "Graduation recognition conditions.",
    },
    {
        "doc_id": "ug_regulations_hub",
        "source_url": "https://undergrad.tdtu.edu.vn/hoc-vu/quy-che-quy-dinh",
        "source_type": "html",
        "domain": "regulation",
        "authority_level": "official",
        "status": "active",
        "notes": "Official regulations hub.",
    },
    {
        "doc_id": "ug_moet_undergrad_regulation",
        "source_url": "https://undergrad.tdtu.edu.vn/hoc-vu/quy-che-dao-tao-trinh-do-dai-hoc",
        "source_type": "html",
        "domain": "regulation",
        "authority_level": "official",
        "status": "active",
        "notes": "Public page summarizing the national undergraduate regulation.",
    },
    {
        "doc_id": "ug_training_reg_k2020_html",
        "source_url": "https://undergrad.tdtu.edu.vn/hoc-vu/quy-che-chuc-va-quan-ly-dao-tao-trinh-do-dai-hoc-khoa-ts2020-tro-ve-truoc",
        "source_type": "html",
        "domain": "training_regulation",
        "authority_level": "official",
        "status": "outdated",
        "notes": "Applies to enrollment cohorts 2020 and earlier.",
    },
    {
        "doc_id": "ug_training_reg_k2021_html",
        "source_url": "https://undergrad.tdtu.edu.vn/hoc-vu/quy-che-chuc-va-quan-ly-dao-tao-trinh-do-dai-hoc-khoa-ts2021-tro-ve-sau",
        "source_type": "html",
        "domain": "training_regulation",
        "authority_level": "official",
        "status": "active",
        "notes": "Applies to enrollment cohorts 2021 and later.",
    },
    {
        "doc_id": "ug_teaching_learning_rules",
        "source_url": "https://undergrad.tdtu.edu.vn/hoc-vu/quy-dinh-ve-day-hoc-tai-tdtu",
        "source_type": "html",
        "domain": "academic_policy",
        "authority_level": "official",
        "status": "active",
        "notes": "Public teaching and learning rules.",
    },
    {
        "doc_id": "ug_parent_info_policy",
        "source_url": "https://undergrad.tdtu.edu.vn/hoc-vu/quy-dinh-ve-viec-cung-cap-thong-tin-cho-phu-huynh",
        "source_type": "html",
        "domain": "academic_policy",
        "authority_level": "official",
        "status": "active",
        "notes": "Policy on providing information to parents.",
    },
    {
        "doc_id": "ug_student_support",
        "source_url": "https://undergrad.tdtu.edu.vn/hoc-vu/ho-tro-sinh-vien",
        "source_type": "html",
        "domain": "student_guide",
        "authority_level": "official",
        "status": "active",
        "notes": "Support contacts and academic help points.",
    },
    {
        "doc_id": "ug_student_notes",
        "source_url": "https://undergrad.tdtu.edu.vn/huong-dan/sinh-vien-va-nhung-dieu-can-luu-y",
        "source_type": "html",
        "domain": "student_guide",
        "authority_level": "official",
        "status": "active",
        "notes": "Public student note and onboarding guidance.",
    },
    {
        "doc_id": "ug_student_life",
        "source_url": "https://undergrad.tdtu.edu.vn/huong-dan/sinh-vien-tdtu",
        "source_type": "html",
        "domain": "student_guide",
        "authority_level": "official",
        "status": "active",
        "notes": "Student conduct and campus life guidance.",
    },
    {
        "doc_id": "ug_academic_year_plan_page",
        "source_url": "https://undergrad.tdtu.edu.vn/hoc-vu/ke-hoach-hoc-tap-nam-hoc",
        "source_type": "html",
        "domain": "academic_schedule",
        "authority_level": "official",
        "status": "active",
        "notes": "Academic year plan page.",
    },
    {
        "doc_id": "ug_campus_utilities",
        "source_url": "https://undergrad.tdtu.edu.vn/hoc-vu/cac-tien-ich-khi-hoc-tai-tdtu",
        "source_type": "html",
        "domain": "student_guide",
        "authority_level": "official",
        "status": "active",
        "notes": "Campus utilities and study infrastructure overview.",
    },
    {
        "doc_id": "it_cs_program_overview",
        "source_url": "https://it.tdtu.edu.vn/nganh-khoa-hoc-may-tinh",
        "source_type": "html",
        "domain": "curriculum",
        "authority_level": "faculty",
        "status": "active",
        "notes": "Computer Science major overview page.",
    },
    {
        "doc_id": "it_cs_program_detail",
        "source_url": "https://it.tdtu.edu.vn/giao-duc/nganh-khoa-hoc-may-tinh",
        "source_type": "html",
        "domain": "curriculum",
        "authority_level": "faculty",
        "status": "active",
        "notes": "Faculty program detail page for Computer Science.",
    },
    {
        "doc_id": "it_cs_elo_2015",
        "source_url": "https://it.tdtu.edu.vn/chuan-dau-ra-2015-nganh-khoa-hoc-may-tinh-chuong-trinh-tieu-chuan",
        "source_type": "html",
        "domain": "curriculum",
        "authority_level": "faculty",
        "status": "outdated",
        "notes": "2015 expected learning outcomes for Computer Science.",
    },
    {
        "doc_id": "it_cs_elo_2018",
        "source_url": "https://it.tdtu.edu.vn/chuan-dau-ra-2018-nganh-khoa-hoc-may-tinh-chuong-trinh-tieu-chuan",
        "source_type": "html",
        "domain": "curriculum",
        "authority_level": "faculty",
        "status": "outdated",
        "notes": "2018 expected learning outcomes for Computer Science.",
    },
    {
        "doc_id": "it_cs_curriculum_2015",
        "source_url": "https://it.tdtu.edu.vn/chuong-trinh-dao-tao-2015-nganh-khoa-hoc-may-tinh-ma-nganh-7480101-chuong-trinh-tieu-chuan",
        "source_type": "html",
        "domain": "curriculum",
        "authority_level": "faculty",
        "status": "outdated",
        "notes": "2015 curriculum for Computer Science.",
    },
    {
        "doc_id": "it_cs_curriculum_2018",
        "source_url": "https://it.tdtu.edu.vn/chuong-trinh-dao-tao-2018-nganh-khoa-hoc-may-tinh-ma-nganh-7480101-chuong-trinh-tieu-chuan",
        "source_type": "html",
        "domain": "curriculum",
        "authority_level": "faculty",
        "status": "outdated",
        "notes": "2018 curriculum for Computer Science.",
    },
    {
        "doc_id": "tdtu_undergraduate_hub",
        "source_url": "https://www.tdtu.edu.vn/giao-duc/dai-hoc",
        "source_type": "html",
        "domain": "curriculum",
        "authority_level": "official",
        "status": "active",
        "notes": "Main undergraduate education overview page.",
    },
    {
        "doc_id": "tdtu_academic_guidance",
        "source_url": "https://www.tdtu.edu.vn/giao-duc/huong-dan-hoc-vu",
        "source_type": "html",
        "domain": "student_guide",
        "authority_level": "official",
        "status": "active",
        "notes": "Main site academic guidance page.",
    },
    {
        "doc_id": "tdtu_training_regulations",
        "source_url": "https://www.tdtu.edu.vn/giao-duc/dai-hoc/quy-che-dao-tao",
        "source_type": "html",
        "domain": "training_regulation",
        "authority_level": "official",
        "status": "active",
        "notes": "Main site training regulations page.",
    },
    {
        "doc_id": "tdtu_major_catalog",
        "source_url": "https://www.tdtu.edu.vn/giao-duc/danh-muc-nganh-hoc",
        "source_type": "html",
        "domain": "curriculum",
        "authority_level": "official",
        "status": "active",
        "notes": "Official major catalog.",
    },
    {
        "doc_id": "admission_handbook_2025",
        "source_url": "https://admission.tdtu.edu.vn/sites/admission/files/Tuyen-sinh/2025/Huong-dan-thu-tuc-nhap-hoc/7.Nhung-dieu-can-biet-khi-hoc-tai-TDTU-2025.pdf",
        "source_type": "pdf",
        "domain": "admission",
        "authority_level": "official",
        "status": "active",
        "notes": "2025 public admission/student handbook PDF.",
        "title_override": "Những điều cần biết khi học tại TDTU 2025",
    },
    {
        "doc_id": "admission_handbook_2022",
        "source_url": "https://admission.tdtu.edu.vn/sites/admission/files/Tuyen-sinh/2022/TB%20trung%20tuyen/Nhung%20dieu%20can%20biet%20khi%20hoc%20tai%20TDTU%202022.pdf",
        "source_type": "pdf",
        "domain": "admission",
        "authority_level": "official",
        "status": "outdated",
        "notes": "2022 public admission/student handbook PDF.",
        "title_override": "Những điều cần biết khi học tại TDTU 2022",
    },
    {
        "doc_id": "ug_training_reg_k2020_pdf",
        "source_url": "https://undergrad.tdtu.edu.vn/sites/undergrad/files/Undergrad/Vanban/2019_Quy%20ch%E1%BA%BF%20t%E1%BB%95%20ch%E1%BB%A9c%20v%C3%A0%20qu%E1%BA%A3n%20l%C3%BD%20%C4%91%C3%A0o%20t%E1%BA%A1o%20tr%C3%ACnh%20%C4%91%E1%BB%99%20%C4%91%E1%BA%A1i%20h%E1%BB%8Dc%20%28T%C3%ADch%20h%E1%BB%A3p%20Q%C4%90%201174_Q%C4%90-T%C4%90T%20v%C3%A0%20Q%C4%90%202444_Q%C4%90-T%C4%90T%29.pdf",
        "source_type": "pdf",
        "domain": "training_regulation",
        "authority_level": "official",
        "status": "outdated",
        "notes": "Integrated regulation PDF for cohorts up to 2020.",
        "title_override": "Quy chế tổ chức và quản lý đào tạo trình độ đại học - khóa TS2020 trở về trước",
    },
    {
        "doc_id": "ug_training_reg_k2021_pdf",
        "source_url": "https://undergrad.tdtu.edu.vn/sites/undergrad/files/Undergrad/Vanban/Q%C4%90%2C1830_Quy%20ch%E1%BA%BF%20t%E1%BB%95%20ch%E1%BB%A9c%20v%C3%A0%20qu%E1%BA%A3n%20l%C3%BD%20%C4%91%C3%A0o%20t%E1%BA%A1o%20tuy%E1%BB%83n%20sinh%202021.pdf",
        "source_type": "pdf",
        "domain": "training_regulation",
        "authority_level": "official",
        "status": "active",
        "notes": "Official regulation PDF for cohorts from 2021.",
        "title_override": "Quy chế tổ chức và quản lý đào tạo trình độ đại học - khóa TS2021 trở về sau",
    },
    {
        "doc_id": "ug_english_placement_score_guide_pdf",
        "source_url": "https://undergrad.tdtu.edu.vn/sites/undergrad/files/Undergrad/2024/6%20-%202024_H%C6%B0%E1%BB%9Bng%20d%E1%BA%ABn%20xem%20%C4%91i%E1%BB%83m%20thi%20x%E1%BA%BFp%20l%E1%BB%9Bp%20ti%E1%BA%BFng%20Anh.pdf",
        "source_type": "pdf",
        "domain": "student_guide",
        "authority_level": "official",
        "status": "active",
        "notes": "Public PDF guide for viewing English placement scores.",
        "title_override": "Hướng dẫn xem điểm thi xếp lớp tiếng Anh",
    },
]
